[Bug] Fix a bug that causing error when setting `write.data.path` to be a subdirectory of the table location (#3371)
Currently, when updating write.data.path of the table to a subdir under the table location, it will fail the location overlap check. For example

spark-sql> ALTER TABLE tb1 SET TBLPROPERTIES (
  'write.data.path' = '<tableLocation>/alternative_data'
);

org.apache.iceberg.exceptions.ForbiddenException: Forbidden: Unable to create table at location 's3://<table_location>' because it conflicts with existing table or namespace at location 's3://<table_location>`
IcebergCatalog.validateNoLocationOverlap(...) constructs a virtual PolarisEntity for overlap checking, but it did not set the entity name. When fetching the siblings of the table, it fails to filter out itself and thus the check mistaken considered that the write.data.path conflict with the table's own base location. (isChildOf)

This PR fix the issue by adding name to the virtual PolarisEntity and add a unit and a integration test.