Non-breaking code updates for new errorprone version
This change is required for #1213

From [CI](https://github.com/apache/polaris/actions/runs/13952639581/job/39055890829]:
```
/home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java:188: error: [PatternMatchingInstanceof] This code can be simplified to use a pattern-matching instanceof.
        (baseCatalog instanceof SupportsNamespaces) ? (SupportsNamespaces) baseCatalog : null;
                     ^
    (see https://errorprone.info/bugpattern/PatternMatchingInstanceof)
  Did you mean '(baseCatalog instanceof SupportsNamespaces supportsNamespaces) ? supportsNamespaces : null;'?
/home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java:189: error: [PatternMatchingInstanceof] This code can be simplified to use a pattern-matching instanceof.
    this.viewCatalog = (baseCatalog instanceof ViewCatalog) ? (ViewCatalog) baseCatalog : null;
                                    ^
    (see https://errorprone.info/bugpattern/PatternMatchingInstanceof)
  Did you mean 'this.viewCatalog = (baseCatalog instanceof ViewCatalog viewCatalog) ? viewCatalog : null;'?

> Task :polaris-service-common:compileJava
/home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java:676: error: [PatternMatchingInstanceof] This code can be simplified to use a pattern-matching instanceof.
      if (baseCatalog instanceof BasePolarisCatalog) {
                      ^
    (see https://errorprone.info/bugpattern/PatternMatchingInstanceof)
  Did you mean 'if (baseCatalog instanceof BasePolarisCatalog basePolarisCatalog) {'?
/home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java:899: error: [PatternMatchingInstanceof] This code can be simplified to use a pattern-matching instanceof.
                  if (baseCatalog instanceof BasePolarisCatalog
                                  ^
    (see https://errorprone.info/bugpattern/PatternMatchingInstanceof)
  Did you mean 'if (baseCatalog instanceof BasePolarisCatalog basePolarisCatalog'?
/home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java:900: error: [PatternMatchingInstanceof] This code can be simplified to use a pattern-matching instanceof.
                      && update instanceof MetadataUpdate.SetLocation) {
                                ^
    (see https://errorprone.info/bugpattern/PatternMatchingInstanceof)
  Did you mean '&& update instanceof MetadataUpdate.SetLocation setLocation) {'?
/home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java:1022: error: [PatternMatchingInstanceof] This code can be simplified to use a pattern-matching instanceof.
    if (!(baseCatalog instanceof BasePolarisCatalog)) {
                      ^
    (see https://errorprone.info/bugpattern/PatternMatchingInstanceof)
  Did you mean 'if (!(baseCatalog instanceof BasePolarisCatalog basePolarisCatalog)) {'?
/home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java:1039: error: [PatternMatchingInstanceof] This code can be simplified to use a pattern-matching instanceof.
              if (!(table instanceof BaseTable)) {
                          ^
    (see https://errorprone.info/bugpattern/PatternMatchingInstanceof)
  Did you mean 'if (!(table instanceof BaseTable baseTable)) {'?
/home/runner/work/polaris/polaris/service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java:1064: error: [PatternMatchingInstanceof] This code can be simplified to use a pattern-matching instanceof.
                        if (singleUpdate instanceof MetadataUpdate.SetLocation) {
                                         ^
    (see https://errorprone.info/bugpattern/PatternMatchingInstanceof)
  Did you mean 'if (singleUpdate instanceof MetadataUpdate.SetLocation setLocation) {'?
```